version: 0.0
os: linux
permissions:
  - object: /
    pattern: "**/*"
    owner: ec2-user
    group: ec2-user
files:
  - source: /
    destination: /home/ec2-user/myzoom
hooks:
  ApplicationStop:
    - location: scripts/stop_hook.sh
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install_hook.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_hook.sh
      timeout: 300
      runas: ec2-user
artifacts:
  files:
    - '**/*'