version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myzoom
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_hook
      timeout: 10
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install_hook
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_hook
      timeout: 10
      runas: ec2-user