version: 0.0
os: linux
artifacts:
  files:
    - '**/*'
files:
  - source: /
    destination: /home/ec2-user/myzoom
hooks:
  AplicationStart:
    - location: scripts/StartHook.sh
      timeout: 300
      runas: ec2-user