version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
hooks:
#  BeforeInstall:
#    - location: scripts/start_serve
#      timeout: 300
  AfterInstall:
    - location: scripts/start_server
      timeout: 300