version: 0.0
os: linux
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
files:
  - source: /
    destination: /home/ubuntu/myzoom
hooks:
  ApplicationStop:
    - location: scripts/stop_hook
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install_hook
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_hook
      timeout: 300
      runas: ubuntu