version: 0.1
os: linux
files:
  - source: /
    destination: /home/ec2-user/myzoom
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
  AfterInstall:
    - location: scripts/StartHook.sh
      timeout: 300