version: 0.2
os: linux
files:
  - source: /
    destination: /home/ec2-user/myzoom
hooks:
  ApplicationStop:
    - location: scripts/stop_hook.sh
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install_hook.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_hook.sh
      timeout: 300
      runas: ec2-user
artifacts:
  files:
    - '**/*'