#!/bin/bash

#give permission for everything in the express-app directory
sudo chmod -R 777 /home/ec2-user/myzoom

#navigate into our working directory where we have all our github files
cd /home/ec2-user/myzoom

#add npm and node to path
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # loads nvm bash_completion (node is in path now)

#install node modules
npm install


npm install -g pm2

cd /home/ec2-user/myzoom/src
pm2 stop mi-zoom

# restart pm2 and thus node app on reboot
crontab -l | { cat; echo "@reboot sudo pm2 start index.js -i 0 --name \"mi-zoom\""; } | crontab -
# start the server
pm2 start index.js -i 0 --name "mi-zoom"
